# Generated by Django 5.0.6 on 2024-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField(max_length=500)),
            ],
        ),
    ]
